DROP TABLE IF EXISTS posts CASCADE;
CREATE TABLE posts(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    body TEXT,
    likes INTEGER,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);